apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: "o2platformcluster-397a"
    labels:
        app: "o2platformcluster-397a"
    annotations:
        # kubernetes.io/ing#ress.class: addon-http-application-routing
        # kubernetes.io/ingress.class: nginx
        # certmanager.k8s.io/acme-challenge-type: http01
        cert-manager.io/issuer: letsencrypt-prod
        # certmanager.k8s.io/cluster-issuer: letsencrypt-prod
spec:
    tls:
        - hosts:
          - tls-prod-o2platformcluster-397a.cedc7c6f3e354120aaa6.eastus.aksapp.io
          secretName: o2-letsencrypt-prod
    rules:
        - host: tls-prod-o2platformcluster-397a.cedc7c6f3e354120aaa6.eastus.aksapp.io
          http:
            paths:
            - path: /
              backend:
                serviceName: "o2platformcluster-397a"
                servicePort: 80
