apiVersion: v1
kind: Service
metadata:
  name: {{ include "o2-identity.fullname" . }}
  labels:
    {{- include "o2-identity.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: 80
  selector:
    {{- include "o2-identity.selectorLabels" . | nindent 4 }}
