# This is a basic workflow to help you get started with Actions

name: Docker Image Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@master
    - name: Build docker image
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/O2.Identity.Web" -f  "O2.Identity.Web/Dockerfile" -t o2bionics.azurecr.io/o2-identity-web:${{ github.sha }}
        docker build "$GITHUB_WORKSPACE/O2.Identity.Web" -f  "O2.Identity.Web/Dockerfile" -t o2bionics/o2-identity-web:${{ github.sha }}
