name: .NET Core Build

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.108
      - name: Install dependencies
        run: dotnet restore O2.Identity.Web/O2.Identity.Web.csproj 
      - name: Build
        run: dotnet build O2.Identity.Web/O2.Identity.Web.csproj --configuration Release --no-restore
      - name: Test
        run: dotnet test O2.Identity.Web/O2.Identity.Web.csproj --no-restore --verbosity normal